import {
  Anchor,
  Apple,
  Archive,
  Award,
  BadgeCheck,
  Ban,
  BatteryCharging,
  Beaker,
  Beef,
  Bird,
  Bone,
  Boxes,
  Bubbles,
  Candy,
  CandyOff,
  Barrel,
  CalendarX2,
  Cherry,
  ChefHat,
  CircleCheck,
  CircleDashed,
  CircleOff,
  CircleSlash,
  CircleSlash2,
  Citrus,
  Clock,
  CloudDrizzle,
  Cookie,
  CookingPot,
  CopyPlus,
  Coffee,
  Container,
  Cpu,
  Dumbbell,
  DoorOpen,
  Droplet,
  Droplets,
  Drumstick,
  EggOff,
  Feather,
  Fish,
  FishOff,
  Flame,
  FlameKindling,
  FlaskConical,
  Flower2,
  Gauge,
  GaugeCircle,
  Gem,
  Grape,
  Grip,
  GripVertical,
  Hammer,
  Hand,
  Handshake,
  Ham,
  HeartPulse,
  History,
  Hourglass,
  IceCreamCone,
  LayoutGrid,
  Layers,
  Layers2,
  Layers3,
  Leaf,
  LeafyGreen,
  MapPin,
  Medal,
  MilkOff,
  Minimize2,
  Mountain,
  Nut,
  NutOff,
  Package,
  PackageCheck,
  PackageOpen,
  PiggyBank,
  Recycle,
  Rose,
  Sailboat,
  Salad,
  Scissors,
  Shell,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Ship,
  Smile,
  Snowflake,
  Soup,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Sun,
  SunMedium,
  Thermometer,
  ThermometerSnowflake,
  Tractor,
  Trees,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Vault,
  Vegan,
  Verified,
  Waves,
  Weight,
  Wheat,
  WheatOff,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { FIGS_ATTRIBUTES } from './stashTaxonomy'

type AttributeMeta = { Icon: LucideIcon; color: string }

/** One fully-distinct icon (+ color) per figs attribute — no two attributes share a glyph. */
export const ATTRIBUTE_META: Record<(typeof FIGS_ATTRIBUTES)[number], AttributeMeta> = {
  vegan: { Icon: Vegan, color: '#4C6A57' },
  vegetarian: { Icon: Salad, color: '#5B7A61' },
  'gluten-free': { Icon: WheatOff, color: '#B4823F' },
  'dairy-free': { Icon: MilkOff, color: '#4A6FA5' },
  'nut-free': { Icon: NutOff, color: '#A2472F' },
  'soy-free': { Icon: CircleSlash, color: '#A2472F' },
  organic: { Icon: Sprout, color: '#708A7C' },
  'non-GMO': { Icon: ShieldCheck, color: '#3D5C48' },
  'grass-fed': { Icon: Tractor, color: '#8B6F47' },
  'free-range': { Icon: Bird, color: '#B08650' },
  'pasture-raised': { Icon: Mountain, color: '#7A6A50' },
  'wild-caught': { Icon: Fish, color: '#2E6B8A' },
  local: { Icon: MapPin, color: '#A24433' },
  'farm-fresh': { Icon: Sun, color: '#D1712F' },
  'High-Protein': { Icon: Dumbbell, color: '#5B4A8A' },
  'Low-Carb': { Icon: TrendingDown, color: '#5B4A8A' },
  Keto: { Icon: Flame, color: '#5B4A8A' },
  'Sugar-Free': { Icon: CandyOff, color: '#5B4A8A' },
  'No Added Sugar': { Icon: Candy, color: '#5B4A8A' },
  'Low-Sodium': { Icon: Droplet, color: '#5B4A8A' },
  Probiotic: { Icon: FlaskConical, color: '#3D5C87' },
  Fermented: { Icon: Beaker, color: '#3D5C87' },
  Kosher: { Icon: BadgeCheck, color: '#1A0D40' },
  Halal: { Icon: Award, color: '#1A0D40' },
  'plant-based': { Icon: Leaf, color: '#4C6A57' },
  perishable: { Icon: Clock, color: '#C77F2E' },
  stable: { Icon: Shield, color: '#6B7280' },
  'pantry-staple': { Icon: Package, color: '#A6875A' },
  'fiber-rich': { Icon: Wheat, color: '#8B6F47' },
  pescatarian: { Icon: Anchor, color: '#2E7A8A' },
  paleo: { Icon: Drumstick, color: '#8B5A2B' },
  umami: { Icon: Soup, color: '#6B3F3F' },
  acidic: { Icon: Citrus, color: '#8FA831' },
  spicy: { Icon: TriangleAlert, color: '#C0392B' },
  sweet: { Icon: Cookie, color: '#D66B8C' },
  bitter: { Icon: Coffee, color: '#4A3728' },
  earthy: { Icon: Trees, color: '#5C6B4A' },
  'calorie-dense': { Icon: Zap, color: '#E0791A' },
  'low-calorie': { Icon: Feather, color: '#6FA8C4' },
  'egg-free': { Icon: EggOff, color: '#A2472F' },
  'shellfish-free': { Icon: Shell, color: '#2E6B8A' },
  'seafood-free': { Icon: FishOff, color: '#1B5E7A' },
  'sesame-free': { Icon: CircleSlash2, color: '#A2472F' },
  'nightshade-free': { Icon: CircleDashed, color: '#7A4A6B' },
  'allium-free': { Icon: Ban, color: '#9A5A3A' },
  'low-FODMAP': { Icon: GaugeCircle, color: '#5B4A8A' },
  AIP: { Icon: ShieldPlus, color: '#4A3F7A' },
  carnivore: { Icon: Beef, color: '#8B5A2B' },
  whole30: { Icon: Medal, color: '#1A0D40' },
  Mediterranean: { Icon: Sailboat, color: '#2E7A8A' },
  regenerative: { Icon: Recycle, color: '#4C6A57' },
  'fair-trade': { Icon: Handshake, color: '#B08650' },
  'sustainably-sourced': { Icon: LeafyGreen, color: '#5B7A61' },
  'line-caught': { Icon: Ship, color: '#17607A' },
  'cage-free': { Icon: DoorOpen, color: '#C48A4A' },
  'non-irradiated': { Icon: Verified, color: '#6B7280' },
  raw: { Icon: Apple, color: '#7A9A3D' },
  'cold-pressed': { Icon: Droplets, color: '#3D6B8A' },
  unrefined: { Icon: PackageOpen, color: '#A6875A' },
  artisanal: { Icon: Hammer, color: '#8B6F47' },
  'batch-crafted': { Icon: Barrel, color: '#6B4F2F' },
  'low-fat': { Icon: Minimize2, color: '#5B4A8A' },
  'zero-carb': { Icon: CircleOff, color: '#5B4A8A' },
  'electrolyte-rich': { Icon: BatteryCharging, color: '#2E86AB' },
  'iron-rich': { Icon: Weight, color: '#6B4F3A' },
  'calcium-rich': { Icon: Bone, color: '#8A8478' },
  'omega-3-rich': { Icon: Waves, color: '#2E7A9A' },
  'antioxidant-rich': { Icon: Star, color: '#8A5FBF' },
  'low-glycemic': { Icon: Gauge, color: '#4A6FA5' },
  'heart-healthy': { Icon: HeartPulse, color: '#B23A5A' },
  salty: { Icon: Container, color: '#6B7280' },
  savory: { Icon: ChefHat, color: '#6B4A3F' },
  smoky: { Icon: FlameKindling, color: '#5A4638' },
  tangy: { Icon: Grape, color: '#9AAE3D' },
  tart: { Icon: Cherry, color: '#A83E5C' },
  citrusy: { Icon: SunMedium, color: '#E8A23D' },
  herbal: { Icon: Flower2, color: '#6B8E4E' },
  nutty: { Icon: Nut, color: '#7A5C3D' },
  floral: { Icon: Rose, color: '#C97BA8' },
  peppery: { Icon: Sparkle, color: '#5C3A2A' },
  funky: { Icon: Sparkles, color: '#7A5C8A' },
  crunchy: { Icon: Grip, color: '#B4823F' },
  crispy: { Icon: GripVertical, color: '#C4923F' },
  creamy: { Icon: IceCreamCone, color: '#C9A876' },
  velvety: { Icon: Bubbles, color: '#B08CA0' },
  tender: { Icon: Scissors, color: '#A8785A' },
  chewy: { Icon: Layers3, color: '#8A6F4A' },
  flaky: { Icon: Layers2, color: '#C4A876' },
  juicy: { Icon: CloudDrizzle, color: '#4A7FA5' },
  thick: { Icon: Layers, color: '#6B5A47' },
  dense: { Icon: Layers, color: '#5A4A3A' },
  rich: { Icon: Gem, color: '#8A6F1F' },
  light: { Icon: Wind, color: '#A8C4D8' },
  brothy: { Icon: CookingPot, color: '#8A6A4A' },
  neutral: { Icon: CircleDashed, color: '#9a9aa0' },
  'freezer-stable': { Icon: Snowflake, color: '#4A7FA8' },
  chilled: { Icon: ThermometerSnowflake, color: '#5A8FBF' },
  'shelf-stable': { Icon: Vault, color: '#8A8272' },
  'quick-decay': { Icon: CalendarX2, color: '#C0503A' },
  aged: { Icon: History, color: '#7A6A5A' },
  cured: { Icon: Ham, color: '#B25A3A' },
  dried: { Icon: PackageCheck, color: '#A67C4A' },
  dehydrated: { Icon: Boxes, color: '#9A8560' },
  canned: { Icon: Archive, color: '#6B7280' },
}

/** Recipe-only attributes — additive to `ATTRIBUTE_META`, describes the dish as a whole rather
 * than a single ingredient. Recipes display both this set and the full ingredient-attribute set. */
export const RECIPE_ATTRIBUTES = [
  'kid-friendly',
  'host-worthy',
  'budget-friendly',
  'batch-friendly',
  'crunchy',
  'creamy',
  'broth-based',
  'charred',
  'high-stash-impact',
  'ready-to-eat',
  'garnish/finisher',
  'low-touch',
  'active-prep',
  'technical',
  'one-pot',
  'sheet-pan',
  'sous-vide',
  'raw/no-cook',
  'air-fryer',
  'quick',
  'moderate',
  'slow-cook',
] as const

export type RecipeAttribute = (typeof RECIPE_ATTRIBUTES)[number]

export const RECIPE_ATTRIBUTE_META: Record<RecipeAttribute, AttributeMeta> = {
  'kid-friendly': { Icon: Smile, color: '#E0A83E' },
  'host-worthy': { Icon: Sparkles, color: '#8A5FBF' },
  'budget-friendly': { Icon: PiggyBank, color: '#4C8B5F' },
  'batch-friendly': { Icon: CopyPlus, color: '#5B7A9A' },
  crunchy: { Icon: Grip, color: '#B4823F' },
  creamy: { Icon: Droplets, color: '#C9A876' },
  'broth-based': { Icon: Soup, color: '#8A6A4A' },
  charred: { Icon: Flame, color: '#A2472F' },
  'high-stash-impact': { Icon: TrendingUp, color: '#4C6A57' },
  'ready-to-eat': { Icon: CircleCheck, color: '#3D5C48' },
  'garnish/finisher': { Icon: Sparkle, color: '#8A5FBF' },
  'low-touch': { Icon: Feather, color: '#6FA8C4' },
  'active-prep': { Icon: Hand, color: '#C0503A' },
  technical: { Icon: Cpu, color: '#5B4A8A' },
  'one-pot': { Icon: CookingPot, color: '#8B6F47' },
  'sheet-pan': { Icon: LayoutGrid, color: '#7A6A50' },
  'sous-vide': { Icon: Thermometer, color: '#2E6B8A' },
  'raw/no-cook': { Icon: Snowflake, color: '#4A6FA5' },
  'air-fryer': { Icon: Wind, color: '#708A7C' },
  quick: { Icon: Zap, color: '#E0791A' },
  moderate: { Icon: Gauge, color: '#B08650' },
  'slow-cook': { Icon: Hourglass, color: '#6B3F3F' },
}

const RECIPE_META_LOOKUP = new Map<string, AttributeMeta>(
  Object.entries(RECIPE_ATTRIBUTE_META).map(([k, v]) => [k.toLowerCase(), v]),
)

/** Importance tier list — used for stash-row badge ordering, the edit sheet's chip list, AND
 * ranking a recipe's attribute row (which mixes ingredient-derived and recipe-only attributes).
 * Tiers, most → least decision-relevant:
 *   1. Diet/allergen — determines whether someone even CAN eat it.
 *   2. Recipe-level practical signals — meal-planning relevance (kid-friendly, quick, one-pot...).
 *   3. Sourcing/ethics/quality — how/where it was produced.
 *   4. Nutrient-density call-outs — notable-but-secondary health signals.
 *   5. Flavor/texture/mouthfeel — descriptive, nice-to-know.
 *   6. Shelf-life/storage — least relevant when looking at a dish, more relevant for a stash item. */
export const ATTRIBUTE_PROMINENCE: string[] = [
  // Tier 1 — diet & allergen
  'vegan',
  'vegetarian',
  'plant-based',
  'pescatarian',
  'gluten-free',
  'dairy-free',
  'nut-free',
  'soy-free',
  'egg-free',
  'shellfish-free',
  'seafood-free',
  'sesame-free',
  'nightshade-free',
  'allium-free',
  'Kosher',
  'Halal',
  'Keto',
  'paleo',
  'AIP',
  'whole30',
  'carnivore',
  'Mediterranean',
  'low-FODMAP',
  'High-Protein',
  'Low-Carb',
  'Sugar-Free',
  'No Added Sugar',
  'Low-Sodium',
  'low-fat',
  'zero-carb',
  'low-calorie',
  'low-glycemic',
  'heart-healthy',

  // Tier 2 — recipe-level practical signals
  'kid-friendly',
  'host-worthy',
  'budget-friendly',
  'quick',
  'moderate',
  'slow-cook',
  'one-pot',
  'sheet-pan',
  'air-fryer',
  'sous-vide',
  'raw/no-cook',
  'active-prep',
  'low-touch',
  'technical',
  'batch-friendly',
  'high-stash-impact',
  'ready-to-eat',

  // Tier 3 — sourcing / ethics / quality
  'organic',
  'non-GMO',
  'grass-fed',
  'free-range',
  'pasture-raised',
  'wild-caught',
  'line-caught',
  'cage-free',
  'local',
  'farm-fresh',
  'regenerative',
  'fair-trade',
  'sustainably-sourced',
  'non-irradiated',
  'raw',
  'cold-pressed',
  'unrefined',
  'artisanal',
  'batch-crafted',

  // Tier 4 — nutrient-density call-outs
  'fiber-rich',
  'iron-rich',
  'calcium-rich',
  'omega-3-rich',
  'antioxidant-rich',
  'electrolyte-rich',
  'Probiotic',
  'Fermented',
  'calorie-dense',

  // Tier 5 — flavor / texture / mouthfeel
  'umami',
  'acidic',
  'spicy',
  'sweet',
  'bitter',
  'earthy',
  'salty',
  'savory',
  'smoky',
  'tangy',
  'tart',
  'citrusy',
  'herbal',
  'nutty',
  'floral',
  'peppery',
  'funky',
  'charred',
  'garnish/finisher',
  'crunchy',
  'crispy',
  'creamy',
  'broth-based',
  'velvety',
  'tender',
  'chewy',
  'flaky',
  'juicy',
  'thick',
  'rich',
  'light',
  'brothy',

  // Tier 6 — shelf-life / storage
  'perishable',
  'stable',
  'pantry-staple',
  'freezer-stable',
  'chilled',
  'shelf-stable',
  'quick-decay',
  'aged',
  'cured',
  'dried',
  'dehydrated',
  'canned',
]

const PROMINENCE_INDEX = new Map<string, number>(ATTRIBUTE_PROMINENCE.map((a, i) => [a.toLowerCase(), i]))

/** Sort a set of attribute strings by the shared importance hierarchy. */
export function sortAttributesByProminence(attrs: string[]): string[] {
  return [...attrs].sort((a, b) => {
    const ai = PROMINENCE_INDEX.get(a.toLowerCase()) ?? 99
    const bi = PROMINENCE_INDEX.get(b.toLowerCase()) ?? 99
    return ai - bi
  })
}

export function attributeIcon(attribute: string): LucideIcon {
  return (
    ATTRIBUTE_META[attribute as (typeof FIGS_ATTRIBUTES)[number]]?.Icon ??
    RECIPE_META_LOOKUP.get(attribute.toLowerCase())?.Icon ??
    Sprout
  )
}

export function attributeColor(attribute: string): string {
  return (
    ATTRIBUTE_META[attribute as (typeof FIGS_ATTRIBUTES)[number]]?.color ??
    RECIPE_META_LOOKUP.get(attribute.toLowerCase())?.color ??
    '#6E6E73'
  )
}
