import {
  Apple,
  Banana,
  Beef,
  Beer,
  Cake,
  Candy,
  Carrot,
  Cherry,
  ChefHat,
  Citrus,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Donut,
  Drumstick,
  Egg,
  EggFried,
  Fish,
  Grape,
  Ham,
  IceCream,
  Milk,
  Nut,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  ShoppingBag,
  ShoppingCart,
  Soup,
  Utensils,
  Vegan,
  Wheat,
  Wine,
  type LucideIcon,
} from 'lucide-react'

export const GROCERY_ICON_REGISTRY: { key: string; Icon: LucideIcon }[] = [
  { key: 'shopping-cart', Icon: ShoppingCart },
  { key: 'shopping-bag', Icon: ShoppingBag },
  { key: 'apple', Icon: Apple },
  { key: 'carrot', Icon: Carrot },
  { key: 'beef', Icon: Beef },
  { key: 'fish', Icon: Fish },
  { key: 'milk', Icon: Milk },
  { key: 'egg', Icon: Egg },
  { key: 'wheat', Icon: Wheat },
  { key: 'coffee', Icon: Coffee },
  { key: 'cake', Icon: Cake },
  { key: 'pizza', Icon: Pizza },
  { key: 'salad', Icon: Salad },
  { key: 'ice-cream', Icon: IceCream },
  { key: 'candy', Icon: Candy },
  { key: 'utensils', Icon: Utensils },
  { key: 'chef-hat', Icon: ChefHat },
  { key: 'cherry', Icon: Cherry },
  { key: 'banana', Icon: Banana },
  { key: 'grape', Icon: Grape },
  { key: 'croissant', Icon: Croissant },
  { key: 'sandwich', Icon: Sandwich },
  { key: 'soup', Icon: Soup },
  { key: 'popcorn', Icon: Popcorn },
  { key: 'cookie', Icon: Cookie },
  { key: 'drumstick', Icon: Drumstick },
  { key: 'egg-fried', Icon: EggFried },
  { key: 'citrus', Icon: Citrus },
  { key: 'wine', Icon: Wine },
  { key: 'beer', Icon: Beer },
  { key: 'cup-soda', Icon: CupSoda },
  { key: 'donut', Icon: Donut },
  { key: 'ham', Icon: Ham },
  { key: 'nut', Icon: Nut },
  { key: 'vegan', Icon: Vegan },
]

export const GROCERY_ICON_COLORS = ['#F4F1F9', '#FDECEC', '#FDF2E3', '#EAF5E9', '#E6F0F5', '#EDE7F6', '#EFE9E1']

export function groceryIconFor(key: string | null | undefined): LucideIcon {
  return GROCERY_ICON_REGISTRY.find((i) => i.key === key)?.Icon ?? ShoppingCart
}
